### PR TITLE
membership api migration to tyk

### PR DESCRIPTION
**Pull request by doramatadora**
This supersedes https://github.com/Financial-Times/n-user-api-client/pull/3 

**BREAKING CHANGE**

### CODE REVIEW

**Comment by jonnywyatt** [comment]
lgtm; are all the whitespace changes in here the result of running tslint?

**Comment by doramatadora** [comment]
@jonnywyatt yes, but only in tests as far as I know

**Comment by mclarke47** [comment]
Hi, any progress on this?

**Comment by doramatadora** [comment]
@mclarke47 well yes, I was waiting for your review.

**Comment by mclarke47** [comment]
Divergence is too high, I'm gonna re-do this

**Pull request closed without merging**
